/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.moreno.sortpics.gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import org.moreno.sortpics.model.ImageFileData;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.IntStream;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.ListModel;

import static org.moreno.sortpics.gui.EditTextDialog.showEditTextDialog;

/**
 * @author Fernando Moreno Ruiz <fernandomorenoruiz@gmail.com>
 */
public class FirstPanel extends javax.swing.JPanel {

    /**
     * Creates new form FirstPanel
     */
    public FirstPanel() {
        initComponents();
        attachContextMenu(lsFilesToProcess);
        lbFilesProcessing.setText("");
        lbInfo.setText("");
        btRenameFiles.setVisible(false);
        // Añadir un KeyListener al JList
        lsFilesToProcess.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_DELETE) {
                    // Mostrar cuadro de diálogo de confirmación
                    int response = JOptionPane.showConfirmDialog(
                            null,
                            "¿Está seguro de que desea eliminar el elemento seleccionado?",
                            "Confirmar eliminación",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE
                    );

                    // Eliminar el elemento si el usuario confirma
                    if (response == JOptionPane.YES_OPTION) {
                        //listModel.remove(selectedIndex);
                        // Eliminar el elemento seleccionado
                        try {
                            ImageFileData selectedItem = lsFilesToProcess.getSelectedValue();
                            selectedItem.remove();
                        } catch (IOException ex) {
                            // TODO manage error
                            Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
            }
        });
    }

    public void updateJList(ImageFileData newItem) {
        javax.swing.DefaultListModel<ImageFileData> model = (javax.swing.DefaultListModel<ImageFileData>) lsFilesToProcess.getModel();
        model.addElement(newItem);
    }

    public void updateJList(List<ImageFileData> newItem) {
        // Obtenemos el modelo actual del JList
        javax.swing.DefaultListModel<ImageFileData> model = (javax.swing.DefaultListModel<ImageFileData>) lsFilesToProcess.getModel();

        // Eliminamos todos los elementos existentes en el modelo
        model.removeAllElements();

        // Añadimos los nuevos elementos a partir de la lista proporcionada
        for (ImageFileData imageFileData : newItem) {
            model.addElement(imageFileData);
        }

        // Notificamos al JList que el modelo ha sido modificado (no siempre es necesario, pero es una buena práctica)
        lsFilesToProcess.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbOrderProgress = new javax.swing.JProgressBar();
        btSortPhotos = new javax.swing.JButton();
        tfFolderToOrder = new javax.swing.JTextField();
        chooseFolder = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsFilesToProcess = new javax.swing.JList<>();
        lbFilesProcessing = new javax.swing.JLabel();
        btRenameFiles = new javax.swing.JButton();

        btSortPhotos.setText("Ordenar Fotos");

        tfFolderToOrder.setText("/");

        chooseFolder.setText("Elegir Carpeta");
        chooseFolder.setActionCommand("choose_folder");

        lbInfo.setText("info step");

        lsFilesToProcess.setModel(new DefaultListModel<>());
        jScrollPane2.setViewportView(lsFilesToProcess);

        lbFilesProcessing.setText("files processing");

        btRenameFiles.setText("Confirmar Renombrado");
        btRenameFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRenameFilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFolderToOrder)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btSortPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRenameFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pbOrderProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbInfo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbFilesProcessing)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chooseFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfFolderToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btSortPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btRenameFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbOrderProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbInfo)
                                        .addComponent(lbFilesProcessing))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JList<ImageFileData> getListFilesToProcess() {
        return lsFilesToProcess;
    }

    private void btRenameFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRenameFilesActionPerformed
        var model = lsFilesToProcess.getModel();
        IntStream.range(0, model.getSize()).forEach(ic -> {
            ImageFileData img = model.getElementAt(ic);

        });
    }//GEN-LAST:event_btRenameFilesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRenameFiles;
    private javax.swing.JButton btSortPhotos;
    private javax.swing.JButton chooseFolder;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFilesProcessing;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JList<ImageFileData> lsFilesToProcess;
    private javax.swing.JProgressBar pbOrderProgress;
    private javax.swing.JTextField tfFolderToOrder;
    // End of variables declaration//GEN-END:variables

    public void sortJList() {
        DefaultListModel<ImageFileData> newListModel = new DefaultListModel<>();
        ListModel<ImageFileData> listModel = this.lsFilesToProcess.getModel();
        List<ImageFileData> list = new ArrayList<>();
        for (int i = 0; i < listModel.getSize(); i++) {
            list.add(listModel.getElementAt(i));
        }
        Collections.sort(list);

        newListModel.addAll(list);
        this.lsFilesToProcess.setModel(newListModel);
    }

    public void attachContextMenu(JList<?> list) {
        list.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getButton() == MouseEvent.BUTTON3) { // Clic derecho
                    int index = list.locationToIndex(e.getPoint());
                    if (index != -1) {
                        list.setSelectedIndex(index);
                        JPopupMenu contextMenu = createContextMenu();
                        contextMenu.show(list, e.getX(), e.getY());
                    }
                }
            }
        });
    }

    private JPopupMenu createContextMenu() {
        JPopupMenu contextMenu = new JPopupMenu();
        JMenuItem miBackToOriginalName = new JMenuItem("Renombrar al nombre original");
        JMenuItem miRenameNewName = new JMenuItem("Editar nuevo nombre");
        JMenuItem removeFile = new JMenuItem("Borrar");

        // Agrega un ActionListener al miBackToOriginalName
        miBackToOriginalName.addActionListener(((e) -> {
            // Obtiene el elemento seleccionado en la lista
            ImageFileData selectedItem = lsFilesToProcess.getSelectedValue();
            if (selectedItem != null) {
                try {
                    selectedItem.moveToNoCameraStampName();
                    sortJList();
                } catch (IOException ex) {
                    // TODO manage error
                    Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }));

        miRenameNewName.addActionListener((e -> {
            // Obtiene el elemento seleccionado en la lista
            ImageFileData selectedItem = lsFilesToProcess.getSelectedValue();
            if (selectedItem != null) {
                var newName = showEditTextDialog(null, selectedItem.getNewName());
                selectedItem.setNewName(newName);
                sortJList();
            }
        }));

        removeFile.addActionListener((e) -> {
            try {
                ImageFileData selectedItem = lsFilesToProcess.getSelectedValue();
                selectedItem.remove();
            } catch (IOException ex) {
                // TODO manage error
                Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        });
        contextMenu.add(miBackToOriginalName);
        contextMenu.add(miRenameNewName);
        contextMenu.add(removeFile);

        return contextMenu;
    }

    public void setCellRenderer(ThumbnailListCellRenderer renderer) {
        this.lsFilesToProcess.setCellRenderer(renderer);
    }

    public JButton getBtSortPhotos() {
        return this.btSortPhotos;
    }

    public void setProgressValue(int progress) {
        this.pbOrderProgress.setValue(progress);
    }

    public JLabel getLbInfo() {
        return this.lbInfo;
    }

    public JTextField getTfFolderToOrder() {
        return this.tfFolderToOrder;
    }

    public JButton getBtChooseFolder() {
        return this.chooseFolder;
    }

}
