package org.moreno.sortpics.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;
import org.moreno.sortpics.model.ImageFileData;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Getter
public class FolderAnalyzer {
    JMenuItem menuItemDelete;
    JMenuItem menuItemRename;
    JMenuItem menuItemRemoveCameraTimestamp;
    JMenuItem menuItemRenameToNewName;
    JMenuItem menuItemGetDateFromData;
    JMenuItem menuItemOpenFolder;
    JMenuItem menuItemCopyToSelectedFolder;
    private JButton btChooseFolder;
    private JTextField tfFolderToOrder;
    private JList lsFilesToProcess;
    private JLabel lbInfo;
    private JButton btSortPhotos;
    private JProgressBar pbOrderProgress;
    private JPanel mainPanel;
    private JButton btRenameFiles;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    // constructor
    public FolderAnalyzer() {
        createPopupMenu();
    }

    private void createPopupMenu() {
        // create JPopupMenu with 5 items
        JPopupMenu popupMenu = new JPopupMenu();
        menuItemDelete = new JMenuItem("Delete");
        menuItemRename = new JMenuItem("Edit new name");
        menuItemRemoveCameraTimestamp = new JMenuItem("Remove Camera timestamp format from filename");
        menuItemRenameToNewName = new JMenuItem("Rename to new name");
        menuItemGetDateFromData = new JMenuItem("Get date from Data");
        menuItemOpenFolder = new JMenuItem("Open file location");
        menuItemCopyToSelectedFolder = new JMenuItem("Copy to selection folder");

        popupMenu.add(menuItemRenameToNewName);
        popupMenu.add(menuItemRemoveCameraTimestamp);
        popupMenu.add(menuItemRename);
        popupMenu.add(menuItemDelete);
        popupMenu.add(menuItemGetDateFromData);
        popupMenu.add(menuItemOpenFolder);
        popupMenu.add(menuItemCopyToSelectedFolder);

        // add JPopupMenu to the list
        this.lsFilesToProcess.setComponentPopupMenu(popupMenu);
    }

    public void setCellRenderer(ThumbnailListCellRenderer renderer) {
        this.lsFilesToProcess.setCellRenderer(renderer);
    }

    public void setProgressValue(int progress) {
        this.pbOrderProgress.setValue(progress);
    }

    public void sortJList() {
        DefaultListModel<ImageFileData> newListModel = new DefaultListModel<>();
        ListModel<ImageFileData> listModel = this.lsFilesToProcess.getModel();
        List<ImageFileData> list = new ArrayList<>();
        for (int i = 0; i < listModel.getSize(); i++) {
            list.add(listModel.getElementAt(i));
        }
        Collections.sort(list);

        newListModel.addAll(list);
        this.lsFilesToProcess.setModel(newListModel);
    }

    public void updateJList(List<ImageFileData> listImg) {
        DefaultListModel<ImageFileData> newListModel = new DefaultListModel<>();
        newListModel.addAll(listImg);
        this.lsFilesToProcess.setModel(newListModel);
    }

    public void updateJListModel(ListModel listModel) {
        this.lsFilesToProcess.setModel(listModel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 5, new Insets(0, 0, 0, 0), -1, -1));
        btChooseFolder = new JButton();
        btChooseFolder.setText("Choose Directory");
        mainPanel.add(btChooseFolder, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfFolderToOrder = new JTextField();
        mainPanel.add(tfFolderToOrder, new GridConstraints(0, 3, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbInfo = new JLabel();
        lbInfo.setText("");
        mainPanel.add(lbInfo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btSortPhotos = new JButton();
        btSortPhotos.setText("Process directory");
        mainPanel.add(btSortPhotos, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pbOrderProgress = new JProgressBar();
        mainPanel.add(pbOrderProgress, new GridConstraints(2, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lsFilesToProcess = new JList();
        lsFilesToProcess.setSelectionBackground(new Color(-5604689));
        lsFilesToProcess.setSelectionForeground(new Color(-16708933));
        scrollPane1.setViewportView(lsFilesToProcess);
        btRenameFiles = new JButton();
        btRenameFiles.setText("Rename Files");
        mainPanel.add(btRenameFiles, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
